### ISSUE TITLE
Refocus feature in GUI does not work properly

### ISSUE THREAD

**Issue by pwarciszewski** [mjhoptics/ray-optics#102]
## Description
Hi,
After clicking the "Refocus" function the calculated distance is getting accumulated each time when the function is invoked. As result, the focal plane is getting shifted from the correct position. I believe that the bug is in this line:
https://github.com/mjhoptics/ray-optics/blob/311a030908eed9b7a18ce972a30def706c78257e/src/rayoptics/gui/appcmds.py#L374

## Solution
Replacing ```+=```  with ```=``` seems to solve the issue.

Best,
pwarciszewski

**Comment by mjhoptics** [comment]
Fixed in [this commit](https://github.com/mjhoptics/ray-optics/commit/f4b289f2ccd6ac5b0603f5e270d0fca97eaa0c00)

Thanks for reporting and investigating it. Mike
