### ISSUE TITLE
GUI crashes on bad input

### ISSUE THREAD

**Issue by ajeddeloh** [mjhoptics/ray-optics#13]
Entering invalid data in text boxes crashes the gui since the text is parsed using `eval()`.

I'm happy to fix this but not sure what direction to take:
1) Handle all exceptions from `eval`. I can't think of any that shouldn't be ignored when calling `eval()` in this context?
2) Switch to parsing doubles normally

Was the intent being using eval to allow references to python variables?

**Comment by mjhoptics** [comment]
eval is used in a couple of different places. Which one are you looking at?
In general, I've used the "ignore exceptions until you're forced to handle them" approach. If something can be "fixed" by adding a try block, that's fine. If you don't know if that's the best fix then we have this conversation. :-)
