### ISSUE TITLE
Beamsplitter

### ISSUE THREAD

**Issue by quark159** [mjhoptics/ray-optics#159]
Hi,

I was wondering if it's possible to model beamsplitters with this package? The final goal would be to model a michelson interferometer.

thanks!

**Comment by mjhoptics** [comment]
Hello @quark159,
You cannot trace transmitted and reflected paths in the same ray-optics model. The best you could do is set up two models, a transmitted path model and a reflected path model, evaluate the wavefronts at the exit pupils of both models and manually difference them yourself to get the phase difference. Conceptually simple, but the details are probably messy.
Hope this helps,
Mike Hayford
