### ISSUE TITLE
Help needed with first steps: example eye model

### ISSUE THREAD

**Issue by mmarras** [mjhoptics/ray-optics#18]
Hi, 

I stumbled upon this nice package and thought I give it a spin. I first struggled to get it up and running, but soon realized my python 3.6 was not up for it. Now on python 3.9 it runs like a charm, but unfortunately on this run I bump into issues.

I made a Jupiter notebook trying to model the lenses of the eye. Since opticalglass obviously does not provide the relevant data, I use `opticalglas.glass.calc_glass_constant(nd,nF,nC)[0]` to calculate V-number needed for `sm.add_surface(surf_data)` with `surf_data`  being the list `[curvature, thickness, refractive_index, v-number] `. I think I understood how that works and I think its  fine. 

However, when I put all together it won't plot. I think it has to do with drawing the element box. If I use the same refractive index and V number everywhere it plots just fine. Any idea what is going wrong?

[Eye Notebook](https://github.com/mmarras/mytest/blob/master/eye_LeGrand_nACC.ipynb)

**Comment by mjhoptics** [comment]
Thank you for your report. The crash was due to trying to draw the last element with an rgb=None. The eyewater material fell just outside the glassmap I use to generate element colors.
Thank you for including the notebook to debug the problem.
