### ISSUE TITLE
Cannot import spline

### ISSUE THREAD

**Issue by neherh** [mjhoptics/ray-optics#20]
![Screenshot from 2021-01-28 10-25-11](https://user-images.githubusercontent.com/14037248/106159961-57506b00-6153-11eb-9fa6-345d72ac50d0.png)

I believe the update to optical glass 0.7 needs scipy > 1.3, however the function spline is  only  provided  in scipy < 1.3.

Otherwise, I am getting this error. Can this be updated accordingly, please?

python 3.6
scipy 1.5.4

**Comment by neherh** [comment]
Based on your previous issue, it may seem that I should update to python 3.7?

**Comment by mjhoptics** [comment]
I would update your ray optics version to the current one; the scipy issue was fixed in version 0.4.6. Python 3.7 or greater is needed; I vaguely recall some incompatibility with 3.6.
Thanks

**Comment by neherh** [comment]
Thank you for your reply.
