### ISSUE TITLE
How to building locally

### ISSUE THREAD

**Issue by dibyendumajumdar** [mjhoptics/ray-optics#24]
I assume that if I want to build and install locally all I need to do is this?

```
python setup.py install
```

Thanks and Regards

**Comment by mjhoptics** [comment]
Yes, I believe if you’ve cloned the rayoptics repo, that’s how you update it.

**Comment by dibyendumajumdar** [comment]
okay thank you - appears to work although I had to uninstall rayoptics first to get the update.
