### ISSUE TITLE
Filenames in the zemax module need to be pathlib paths (and this is not documented)

### ISSUE THREAD

**Issue by InfraRedOx** [mjhoptics/ray-optics#26]
Hi there,
I noticed that when trying to use functions from the zemax module (such as read_lens_file), supplying a path as a string will not work, as the first input argument filename is expected to have the methods found in a pathlib Path object (such as "open")
This doesn't seem to be documented.

The fix seems to be to use such a syntax:

filepath = pathlib.Path("subdir/myfile.zmx')
rayoptics.zemax.zmxread.read_lens_file(filepath)

Would it be possible to update the docs to reflect this, or alternatively to enable paths supplied as string objects?

**Comment by mjhoptics** [comment]
Hello @InfraRedOx,
I would recommend using the open_model() function, that is imported from gui.appcmds by environments.py. This will accept strings or filepaths for opening any supported file type (currently Zemax, CODE V, and the native .roa files). I'll update the documentation on read_lens_file to be more specific.
