### ISSUE TITLE
Does this package do exact ray-tracing, or uses the paraxial approximation?

### ISSUE THREAD

**Issue by LaurentRDC** [mjhoptics/ray-optics#51]
Hello,

Thank you for putting together this package! 

I'm looking for a ray-tracing package that does exact ray-tracing, not just paraxial ray-tracing, but I could not determine if this package is suitable.

Can you confirm to me that this package implements exact ray-tracing? If so, you might want to also mention it in the documentation.

Cheers!
Laurent

**Comment by mjhoptics** [comment]
Hello Laurent,
Yes, ray-optics does implement exact, trigonometric, ray tracing. The low level interface is in the raytr.raytrace module; a higher level interface, using relative aperture and field specifications, is in the raytr.trace module. I have a number of jupyter notebooks in my ray-optics-notebooks repo that show how to use ray-optics for different analyses.
Hope this helps.
Mike

**Comment by LaurentRDC** [comment]
Awesome, thank you so much! I will take a look
