### ISSUE TITLE
addsurface

### ISSUE THREAD

**Issue by USTCNing** [mjhoptics/ray-optics#59]
I wat to konw how to use addsurface(class) to creat ray chase。if there is a phase data,how can I get optical chase?

**Comment by mjhoptics** [comment]
Hello,
I encourage you to look at the [Triplet example](https://ray-optics.readthedocs.io/en/latest/examples/TripletExample.html) in the [documentation](https://ray-optics.readthedocs.io/en/latest/index.html). This shows how to enter a Cooke triplet lens using add_surface, what usage parameters are needed for input and some simple ray tracing analyses, including wavefront (phase) aberration plots.
You can also look at the [ray-optics-notebooks](https://github.com/mjhoptics/ray-optics-notebooks) repo for examples of how to use ray-optics in the jupyter notebook environment. There is a [subdirectory of Photo-Patent lenses](https://github.com/mjhoptics/ray-optics-notebooks/tree/master/Photo-Lens-Patents) contributed by @dibyendumajumdar that are extensive examples of the use of add_surface.
Hope this helps.
Mike Hayford
