### ISSUE TITLE
DecenterData.tform_before_surf() can return None as first member of tuple but code doesn't check for None

### ISSUE THREAD

**Issue by dibyendumajumdar** [mjhoptics/ray-optics#62]
I don't know if this is real issue but it makes the type checker unhappy as the tuple member 0 can be None but when this is referenced in the code there is no check.

Example in raytrace.py

```
rt, t = tfrm_from_before
b4_pt, b4_dir = rt.dot(before_pt - t), rt.dot(before_dir)
```

But above rt can be None.

**Comment by mjhoptics** [comment]
You have a point. I made a specific decision to write the lowest level code assuming the inputs (at least the input structures) are correct. This is to avoid having to test everything against a possible `None` or other invalid value. Stated another way, this routine requires all of the inputs to be complete; if they aren't then the results aren't guaranteed. If the inputs cause a ray failure, this is not an input structure problem and try/except statements are used to guard against these kind of data dependent errors.
There are currently only a few places where these transform tuples are computed, see the [sequence](https://ray-optics.readthedocs.io/en/latest/api/rayoptics.seq.html#module-rayoptics.seq.sequential) and [transform](https://ray-optics.readthedocs.io/en/latest/api/rayoptics.elem.html#module-rayoptics.elem.transform) modules.
[trace_raw() ](https://ray-optics.readthedocs.io/en/latest/api/rayoptics.raytr.html#rayoptics.raytr.raytrace.trace_raw) is the primary consumer of the path iterator. I'll add to the doc there the assumption about error free input and also mention the requirement in the [path()](https://ray-optics.readthedocs.io/en/latest/api/rayoptics.seq.html#rayoptics.seq.sequential.SequentialModel.path) method in SequentialModel.
